name: Auto Release v0.1.x

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest v0.1.x tag
        id: get_tag
        run: |
          tag=$(git tag --list 'v0.1.*' --sort=-v:refname | head -n 1)
          echo "Latest tag: $tag"
          if [[ -z "$tag" ]]; then
            echo "version=0.1.0" >> $GITHUB_OUTPUT
          else
            patch=$(echo $tag | cut -d. -f3)
            new_patch=$((patch + 1))
            echo "version=0.1.$new_patch" >> $GITHUB_OUTPUT
          fi

      - name: Create new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.get_tag.outputs.version }}
          git push origin v${{ steps.get_tag.outputs.version }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_tag.outputs.version }}
          name: Release v${{ steps.get_tag.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
